"""Made changes with wallet-user and ticket-user tables

Revision ID: 39cdea1aa973
Revises: 2d79aef39d78
Create Date: 2026-07-13 19:47:28.912963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cdea1aa973'
down_revision = '2d79aef39d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_ticket_user", 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_wallet_user", 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_constraint("fk_wallet_user", type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint("fk_ticket_user", type_='foreignkey')

    # ### end Alembic commands ###
