"""add candy image filename

Revision ID: 7208dc3137f8
Revises: a35d51d73c34
Create Date: 2026-09-01 10:20:56.357877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7208dc3137f8'
down_revision = 'a35d51d73c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user_candy_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transaction_user_candy'))
        batch_op.drop_index(batch_op.f('idx_transaction_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_candy_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_transaction_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_transaction_user_candy'), ['user_id', 'candy_id'], unique=False)

    with op.batch_alter_table('candy', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
