"""added User table

Revision ID: 868e34e1ae0c
Revises: c6b182bb54c8
Create Date: 2026-05-29 17:18:31.645050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868e34e1ae0c'
down_revision = 'c6b182bb54c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
